spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/partner_matcher?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id:
    access-key-secret:
    bucket-name: linkto2026