spring:
  config:
    import:
      - classpath:config.yml
  output:
    ansi:
      enabled: always
  application:
    name: PartnerMatcher
  datasource:
    url: jdbc:mysql://localhost:3306/partner_matcher
    username: ${config.mysql.username}
    password: ${config.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: ${config.redis.password}
    database: 0

mybatis:
  mapper-locations:
    - classpath:mapper/**/*.xml

